'use client';

import type { Metadata } from "next";

import "./globals.css";
import { AuthProvider } from '../context/AuthContext';

// Metadata is not directly used in client components, but kept for consistency
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased flex flex-col min-h-screen"
      >
        <header className="w-full py-4 border-b border-gray-300">
          <div className="container mx-auto text-center">
            <h1 className="text-4xl font-bold text-purple-600">LAZARAFF</h1>
          </div>
        </header>
        <AuthProvider>
          <main className="flex-grow">
            {children}
          </main>
        </AuthProvider>
        <footer className="w-full py-4 border-t border-gray-300 mt-auto">
          <div className="container mx-auto text-center">
            <p className="text-gray-500">&copy; {new Date().getFullYear()} LAZARAFF. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
